export const services = [
  { label: "Artifical Intelligence", link: "/", branches: null },
  { label: "IoT Solution Development", link: "/", branches: null },
  {
    label: "Enterprise Development",
    link: null,
    branches: [
      { label: "Solution Development", link: "/", branches: null },
      { label: "Enterpirse Mobility", link: "/", branches: null },
      { label: "Business Technology Consulting", link: "/", branches: null },
      { label: "Product Engineering", link: "/", branches: null },
      { label: "Product Prototyping", link: "/", branches: null },
      { label: "Digital Transformation", link: "/", branches: null },
    ],
  },
  { label: "Cloud Services", link: "/", branches: null },
  {
    label: "Mobile Application Development",
    link: null,
    branches: [
      { label: "Android Native Development", link: "/", branches: null },
      { label: "IOS Native Development", link: "/", branches: null },
      { label: "React Native Development", link: "/", branches: null },
      { label: "Flutter Application Development", link: "/", branches: null },
      { label: "Ionic Application Development", link: "/", branches: null },
      { label: "IOT Application Development", link: "/", branches: null },
      { label: "Xamarin Application Development", link: "/", branches: null },
    ],
  },
  {
    label: "Custom Web Application Development",
    link: null,
    branches: [
      { label: "Laravel Development", link: "/", branches: null },
      { label: "Angular Development", link: "/", branches: null },
      { label: ".Net Development", link: "/", branches: null },
      { label: "Java Development", link: "/", branches: null },
      { label: "Ecommerce Development", link: "/", branches: null },
      { label: "React Development", link: "/", branches: null },
      { label: "ERP Development", link: "/", branches: null },
      { label: "CRM Development", link: "/", branches: null },
    ],
  },
  {
    label: "Manage Services",
    link: null,
    branches: [
      { label: "Q/A Testing", link: "/", branches: null },
      { label: "Data Migration Services", link: "/", branches: null },
      { label: "Technology Consulting", link: "/", branches: null },
    ],
  },
  { label: "Staff Augmentation", link: "/", branches: null },
  { label: "Embedded Software Development Services", link: "/", branches: null },
  { label: "Blockchain Development", link: "/", branches: null },
]

export const hireDeveloper = [
  { label: "Dedicated Developer", link: "/", branches: null },
  {
    label: "JS & Frontend",
    link: null,
    branches: [
      { label: "Angular Developer", link: "/", branches: null },
      { label: "Vue Developer", link: "/", branches: null },
      { label: "React Developer", link: "/", branches: null },
    ],
  },
  {
    label: "Backend",
    link: null,
    branches: [
      { label: "Laravel Developer", link: "/", branches: null },
      { label: "Java Developer", link: "/", branches: null },
      { label: "Angular Developer", link: "/", branches: null },
      { label: ".Net Developer", link: "/", branches: null },
      { label: "Python Developer", link: "/", branches: null },
      { label: "Flask Developer", link: "/", branches: null },
      { label: "Node JS Developer", link: "/", branches: null },
      { label: "Full Stack Developer", link: "/", branches: null },
    ],
  },
  {
    label: "Ecommerce & CMS",
    link: null,
    branches: [
      { label: "Sitecore Developer", link: "/", branches: null },
      { label: "Sitefinity Developer", link: "/", branches: null },
      { label: "Umbraco Developer", link: "/", branches: null },
      { label: "Sharepoint Developer", link: "/", branches: null },
      { label: "CMS Developer", link: "/", branches: null },
      { label: "Kentico", link: "/", branches: null },
      { label: "eCommerce", link: "/", branches: null },
    ],
  },
  {
    label: "Blockchain & AI",
    link: null,
    branches: [
      { label: "Blockchain Developer", link: "/", branches: null },
      { label: "Machine Learning Developer", link: "/", branches: null },
      { label: "Tensorflow Developer", link: "/", branches: null },
      { label: "Chatbot Developer", link: "/", branches: null },
      { label: "Hyperledger Developer", link: "/", branches: null },
      { label: "Smart Contract Developer", link: "/", branches: null },
      { label: "ICO Developer", link: "/", branches: null },
      { label: "Stellar Developer", link: "/", branches: null },
      { label: "Solidity Developer", link: "/", branches: null },
      { label: "Cryptocurrency Developer", link: "/", branches: null },
    ],
  },
  {
    label: "Mobile",
    link: null,
    branches: [
      { label: "Ionic Developer", link: "/", branches: null },
      { label: "Xaramin Developer", link: "/", branches: null },
      { label: "AR/VR Developer", link: "/", branches: null },
      { label: "Android Developer", link: "/", branches: null },
      { label: "iOS Developer", link: "/", branches: null },
      { label: "Kotlin Developer", link: "/", branches: null },
      { label: "Flutter Developer", link: "/", branches: null },
      { label: "React Native Developer", link: "/", branches: null },
      { label: "Swift Developer", link: "/", branches: null },
      { label: "Titanium Developer", link: "/", branches: null },
      { label: "HTML5 Developer", link: "/", branches: null },
      { label: "Objective C Developer", link: "/", branches: null },
      { label: "xCode Developer", link: "/", branches: null },
    ],
  },
  { label: "Salesforce Developer", link: "/", branches: null },
]

export const navMenu = [
  { label: "About Us", link: "/", tree: null },
  { label: "Services", link: null, tree: [...services] },
  { label: "Hire Developer", link: null, tree: [...hireDeveloper] },
  { label: "Contact", link: "/", tree: null },
  { label: "Career", link: "/", tree: null },
]
