export const services = [
  {
    label: "Artifical Intelligence",
    value: "artificialIntelligence",
    icon: "fas fa-head-side-virus",
    src: "/assets/images/ai/ai_img_1.jpg",
    description:
      "Buld impactful AI/ML solutions to leverage smart analytics and intelligent buisness insights to enhance buisness operations",
    link: "/",
    branches: null,
  },
  {
    label: "IoT Solution Development",
    value: "iotSolutionDevelopment",
    icon: "fas fa-network-wired",
    src: "/assets/images/iot/iot_img_2.jpg",
    description:
      "Build secure IoT and IIoT for your enterprise delivered with benefits of less time to market and high efficiency",
    link: "/",
    branches: null,
  },
  {
    label: "Enterprise Development",
    value: "enterpriseDevelopment",
    icon: "fas fa-handshake",
    src: "/assets/images/enterprise/enterprise_img_1.jpg",
    description: "Result-oriented enterprise development that fuel growth and enhance organizational productivity",
    link: null,
    branches: [
      { label: "Solution Development", icon: "", description: "", link: "/", branches: null },
      { label: "Enterpirse Mobility", icon: "", description: "", link: "/", branches: null },
      { label: "Business Technology Consulting", icon: "", description: "", link: "/", branches: null },
      { label: "Product Engineering", icon: "", description: "", link: "/", branches: null },
      { label: "Product Prototyping", icon: "", description: "", link: "/", branches: null },
      { label: "Digital Transformation", icon: "", description: "", link: "/", branches: null },
    ],
  },
  {
    label: "Cloud Services",
    value: "cloudServices",
    icon: "fas fa-cloud",
    src: "/assets/images/cloud/cloud_img_2.jpg",
    description:
      "Our machine learning and data science practices have helped companies build custom solutions to improve business realities",
    link: "/",
    branches: null,
  },
  {
    label: "Mobile App Development",
    value: "mobileAppDevelopment",
    icon: "fas fa-mobile",
    src: "/assets/images/mobile/mobile_img_2.png",
    description:
      "Mobile application development that offer flawless execution across devices and are tailor-made for user-facing and corporate environment",
    link: null,
    branches: [
      { label: "Android Native Development", icon: "", description: "", link: "/", branches: null },
      { label: "IOS Native Development", icon: "", description: "", link: "/", branches: null },
      { label: "React Native Development", icon: "", description: "", link: "/", branches: null },
      { label: "Flutter Application Development", icon: "", description: "", link: "/", branches: null },
      { label: "Ionic Application Development", icon: "", description: "", link: "/", branches: null },
      { label: "IOT Application Development", icon: "", description: "", link: "/", branches: null },
      { label: "Xamarin Application Development", icon: "", description: "", link: "/", branches: null },
    ],
  },
  {
    label: "Web App Development",
    value: "webAppDevelopment",
    icon: "fas fa-laptop-code",
    src: "/assets/images/web/web_img_2.jpg",
    theme: "#D1FFF1",
    border: "#01594B",
    description:
      "Custom web solutions designed and developed help you augment ROI and transform visitors into rewarding opportunities",
    link: null,
    branches: [
      { label: "Laravel Development", icon: "", description: "", link: "/", branches: null },
      { label: "Angular Development", icon: "", description: "", link: "/", branches: null },
      { label: ".Net Development", icon: "", description: "", link: "/", branches: null },
      { label: "Java Development", icon: "", description: "", link: "/", branches: null },
      { label: "Ecommerce Development", icon: "", description: "", link: "/", branches: null },
      { label: "React Development", icon: "", description: "", link: "/", branches: null },
      { label: "ERP Development", icon: "", description: "", link: "/", branches: null },
      { label: "CRM Development", icon: "", description: "", link: "/", branches: null },
    ],
  },
  {
    label: "Manage Services",
    value: "manageServices",
    icon: "fas fa-users-cog",
    src: "/assets/images/manage-services/ms_img_1.jpg",
    description: "Improve operations and cut the expenses with experts of our team constantly there to help you out",
    link: null,
    branches: [
      { label: "Q/A Testing", link: "/", icon: "", description: "", branches: null },
      { label: "Data Migration Services", icon: "", description: "", link: "/", branches: null },
      { label: "Technology Consulting", icon: "", description: "", link: "/", branches: null },
    ],
  },
  {
    label: "Staff Augmentation",
    value: "staffAugmentation",
    icon: "fas fa-users",
    src: "/assets/images/staff-augmentation/sa_img_1.jpg",
    description:
      "Extend your development team with staff augmentation services that align with your project requirements and won't put a burden on your budget",
    link: "/",
    branches: null,
  },
  {
    label: "Embedded Software Dev",
    value: "embeddedSoftwareDevelopment",
    icon: "fas fa-microchip",
    src: "/assets/images/embedded-software-solutions/ess_img_1.jpg",
    description:
      "Advanced embedded solutions for buisnesses to leverage their connected resources and make the best of them",
    link: "/",
    branches: null,
  },
  {
    label: "Blockchain Development",
    value: "blockchainDevelopment",
    icon: "fab fa-hive",
    src: "/assets/images/blockchain/b_img_1.jpg",
    description:
      "Blockchain development services enhance the capabilities of buisness applications with a variety of tools and technologies for developing secured solutions",
    link: "/",
    branches: null,
  },
]

export const hireDeveloper = [
  { label: "Dedicated Developer", link: "/", branches: null },
  {
    label: "JS & Frontend",
    link: null,
    branches: [
      { label: "Angular Developer", link: "/", branches: null },
      { label: "Vue Developer", link: "/", branches: null },
      { label: "React Developer", link: "/", branches: null },
    ],
  },
  {
    label: "Backend",
    link: null,
    branches: [
      { label: "Laravel Developer", link: "/", branches: null },
      { label: "Java Developer", link: "/", branches: null },
      { label: "Angular Developer", link: "/", branches: null },
      { label: ".Net Developer", link: "/", branches: null },
      { label: "Python Developer", link: "/", branches: null },
      { label: "Flask Developer", link: "/", branches: null },
      { label: "Node JS Developer", link: "/", branches: null },
      { label: "Full Stack Developer", link: "/", branches: null },
    ],
  },
  {
    label: "Ecommerce & CMS",
    link: null,
    branches: [
      { label: "Sitecore Developer", link: "/", branches: null },
      { label: "Sitefinity Developer", link: "/", branches: null },
      { label: "Umbraco Developer", link: "/", branches: null },
      { label: "Sharepoint Developer", link: "/", branches: null },
      { label: "CMS Developer", link: "/", branches: null },
      { label: "Kentico", link: "/", branches: null },
      { label: "eCommerce", link: "/", branches: null },
    ],
  },
  {
    label: "Blockchain & AI",
    link: null,
    branches: [
      { label: "Blockchain Developer", link: "/", branches: null },
      { label: "Machine Learning Developer", link: "/", branches: null },
      { label: "Tensorflow Developer", link: "/", branches: null },
      { label: "Chatbot Developer", link: "/", branches: null },
      { label: "Hyperledger Developer", link: "/", branches: null },
      { label: "Smart Contract Developer", link: "/", branches: null },
      { label: "ICO Developer", link: "/", branches: null },
      { label: "Stellar Developer", link: "/", branches: null },
      { label: "Solidity Developer", link: "/", branches: null },
      { label: "Cryptocurrency Developer", link: "/", branches: null },
    ],
  },
  {
    label: "Mobile",
    link: null,
    branches: [
      { label: "Ionic Developer", link: "/", branches: null },
      { label: "Xaramin Developer", link: "/", branches: null },
      { label: "AR/VR Developer", link: "/", branches: null },
      { label: "Android Developer", link: "/", branches: null },
      { label: "iOS Developer", link: "/", branches: null },
      { label: "Kotlin Developer", link: "/", branches: null },
      { label: "Flutter Developer", link: "/", branches: null },
      { label: "React Native Developer", link: "/", branches: null },
      { label: "Swift Developer", link: "/", branches: null },
      { label: "Titanium Developer", link: "/", branches: null },
      { label: "HTML5 Developer", link: "/", branches: null },
      { label: "Objective C Developer", link: "/", branches: null },
      { label: "xCode Developer", link: "/", branches: null },
    ],
  },
  { label: "Salesforce Developer", link: "/", branches: null },
]

export const navMenu = [
  { label: "About Us", link: "/", tree: null },
  { label: "Services", link: null, tree: [...services] },
  { label: "Hire Developer", link: null, tree: [...hireDeveloper] },
  { label: "Contact", link: "/", tree: null },
  { label: "Career", link: "/", tree: null },
]
