export const servicesTree = [
  { title: "Artifical Intelligence", link: "/", branches: null },
  { title: "IoT Solution Development", link: "/", branches: null },
  {
    title: "Enterprise Development",
    link: null,
    branches: [
      { title: "Solution Development", link: "/", branches: null },
      { title: "Enterpirse Mobility", link: "/", branches: null },
      { title: "Business Technology Consulting", link: "/", branches: null },
      { title: "Product Engineering", link: "/", branches: null },
      { title: "Product Prototyping", link: "/", branches: null },
      { title: "Digital Transformation", link: "/", branches: null },
    ],
  },
  { title: "Cloud Services", link: "/", branches: null },
  {
    title: "Mobile Application Development",
    link: null,
    branches: [
      { title: "Android Native Development", link: "/", branches: null },
      { title: "IOS Native Development", link: "/", branches: null },
      { title: "React Native Development", link: "/", branches: null },
      { title: "Flutter Application Development", link: "/", branches: null },
      { title: "Ionic Application Development", link: "/", branches: null },
      { title: "IOT Application Development", link: "/", branches: null },
      { title: "Xamarin Application Development", link: "/", branches: null },
    ],
  },
  {
    title: "Custom Web Application Development",
    link: null,
    branches: [
      { title: "Laravel Development", link: "/", branches: null },
      { title: "Angular Development", link: "/", branches: null },
      { title: ".Net Development", link: "/", branches: null },
      { title: "Java Development", link: "/", branches: null },
      { title: "Ecommerce Development", link: "/", branches: null },
      { title: "React Development", link: "/", branches: null },
      { title: "ERP Development", link: "/", branches: null },
      { title: "CRM Development", link: "/", branches: null },
    ],
  },
  {
    title: "Manage Services",
    link: null,
    branches: [
      { title: "Q/A Testing", link: "/", branches: null },
      { title: "Data Migration Services", link: "/", branches: null },
      { title: "Technology Consulting", link: "/", branches: null },
    ],
  },
  { title: "Staff Augmentation", link: "/", branches: null },
  { title: "Embedded Software Development Services", link: "/", branches: null },
  { title: "Blockchain Development", link: "/", branches: null },
]

export const hireDeveloperTree = [
  { title: "Dedicated Developer", link: "/", branches: null },
  {
    title: "JS & Frontend",
    link: null,
    branches: [
      { title: "Angular Developer", link: "/", branches: null },
      { title: "Vue Developer", link: "/", branches: null },
      { title: "React Developer", link: "/", branches: null },
    ],
  },
  {
    title: "Backend",
    link: null,
    branches: [
      { title: "Laravel Developer", link: "/", branches: null },
      { title: "Java Developer", link: "/", branches: null },
      { title: "Angular Developer", link: "/", branches: null },
      { title: ".Net Developer", link: "/", branches: null },
      { title: "Python Developer", link: "/", branches: null },
      { title: "Flask Developer", link: "/", branches: null },
      { title: "Node JS Developer", link: "/", branches: null },
      { title: "Full Stack Developer", link: "/", branches: null },
    ],
  },
  {
    title: "Ecommerce & CMS",
    link: null,
    branches: [
      { title: "Sitecore Developer", link: "/", branches: null },
      { title: "Sitefinity Developer", link: "/", branches: null },
      { title: "Umbraco Developer", link: "/", branches: null },
      { title: "Sharepoint Developer", link: "/", branches: null },
      { title: "CMS Developer", link: "/", branches: null },
      { title: "Kentico", link: "/", branches: null },
      { title: "eCommerce", link: "/", branches: null },
    ],
  },
  {
    title: "Blockchain & AI",
    link: null,
    branches: [
      { title: "Blockchain Developer", link: "/", branches: null },
      { title: "Machine Learning Developer", link: "/", branches: null },
      { title: "Tensorflow Developer", link: "/", branches: null },
      { title: "Chatbot Developer", link: "/", branches: null },
      { title: "Hyperledger Developer", link: "/", branches: null },
      { title: "Smart Contract Developer", link: "/", branches: null },
      { title: "ICO Developer", link: "/", branches: null },
      { title: "Stellar Developer", link: "/", branches: null },
      { title: "Solidity Developer", link: "/", branches: null },
      { title: "Cryptocurrency Developer", link: "/", branches: null },
    ],
  },
  {
    title: "Mobile",
    link: null,
    branches: [
      { title: "Ionic Developer", link: "/", branches: null },
      { title: "Xaramin Developer", link: "/", branches: null },
      { title: "AR/VR Developer", link: "/", branches: null },
      { title: "Android Developer", link: "/", branches: null },
      { title: "iOS Developer", link: "/", branches: null },
      { title: "Kotlin Developer", link: "/", branches: null },
      { title: "Flutter Developer", link: "/", branches: null },
      { title: "React Native Developer", link: "/", branches: null },
      { title: "Swift Developer", link: "/", branches: null },
      { title: "Titanium Developer", link: "/", branches: null },
      { title: "HTML5 Developer", link: "/", branches: null },
      { title: "Objective C Developer", link: "/", branches: null },
      { title: "xCode Developer", link: "/", branches: null },
    ],
  },
  { title: "Salesforce Developer", link: "/", branches: null },
]

export const navMenu = [
  { label: "About Us", link: "/", tree: null },
  { label: "Services", link: null, tree: [...servicesTree] },
  { label: "Hire Developer", link: null, tree: [...hireDeveloperTree] },
  { label: "Contact", link: "/", tree: null },
  { label: "Career", link: "/", tree: null },
]
